---
driver:
  name: docker

provisioner:
  name: shell
  data_path: ./

transport:
  username: kitchen

platforms:
  - name: centos-6.7
  - name: centos-7.1
    driver:
      privileged: true
      run_command: /sbin/init

suites:
  - name: setup
    provisioner:
      script: ./test/scripts/setup.sh
  - name: configure
    provisioner:
      script: ./test/scripts/configure.sh
